stages:
- validate-simple-example

#only:
#- master

Validate Simple Example:
  stage: validate-simple-example
  image: johnmorsley/alpine-with-terraform:0.14.2
  script:
  - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
  - export AWS_ACCESS_KEY=$AWS_ACCESS_KEY
  - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  - sh pipeline/scripts/terraform-validate.sh "examples/simple"