stages:
- validate-simple-example
- plan-simple-example
- apply-simple-example
- destroy-simple-example

#only:
#- master

image: johnmorsley/alpine-with-terraform:0.14.2

before_script:
- export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
- export AWS_ACCESS_KEY=$AWS_ACCESS_KEY
- export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

#after_script:
#- whatever.sh

Validate Simple Example:
  stage: validate-simple-example
  #image: johnmorsley/alpine-with-terraform:0.14.2
  before_script:
  - sh pipeline/scripts/terraform-init.sh "examples/simple"
  script:
  - sh pipeline/scripts/terraform-validate.sh "examples/simple"

Plan Simple Example:
  stage: plan-simple-example
  #image: johnmorsley/alpine-with-terraform:0.14.2
  before_script:
  - sh pipeline/scripts/terraform-init.sh "examples/simple"
  #script:
  - sh pipeline/scripts/terraform-plan.sh "examples/simple"

Apply Simple Example:
  stage: apply-simple-example
  #image: johnmorsley/alpine-with-terraform:0.14.2
  before_script:
  - sh pipeline/scripts/terraform-init.sh "examples/simple"
  script:
  - sh pipeline/scripts/terraform-apply.sh "examples/simple"

Destroy Simple Example:
  stage: destroy-simple-example
  #image: johnmorsley/alpine-with-terraform:0.14.2
  before_script:
  - sh pipeline/scripts/terraform-init.sh "examples/simple"
  script:  
  - sh pipeline/scripts/terraform-destroy.sh "examples/simple"  