stages:
- validate
- plan
- apply
- destroy

image: johnmorsley/alpine-with-terraform:0.14.2

before_script:
- export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
- export AWS_ACCESS_KEY=$AWS_ACCESS_KEY
- export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

.template: &template
  only:
  - master

.validate_template: &validate_template
  <<: *template
  stage: validate
  script:
  - sh $CI_PROJECT_DIR/pipeline/scripts/terraform-validate.sh

.plan_template: &plan_template
  <<: *template
  stage: plan
  script:
  - sh $CI_PROJECT_DIR/pipeline/scripts/terraform-plan.sh

validate_simple:
  <<: *validate_template
  before_script:
  - cd examples/simple

validate_complex:
  <<: *validate_template
  before_script:
  - cd examples/complex

# Validate RKE Example:
#   <<: *validate_template
#   before_script:
#   - cd examples/rke

plan_simple:
  <<: *plan_template
  before_script:
  - cd examples/simple
  needs:
  - validate_simple

plan_complex:
  <<: *plan_template
  before_script:
  - cd examples/complex
  needs:
  - validate_complex

# Plan RKE Example:
#   <<: *plan_template
#   before_script:
#   - cd examples/rke

  # Plan Simple Example:
#   <<: *template
#   stage: plan
#   before_script:
#   - cd "examples/simple"
#   script:
#   - sh pipeline/scripts/terraform-plan.sh

# Apply Simple Example:
#   <<: *template
#   stage: apply
#   before_script:
#   - cd "examples/simple"
#   script:
#   - sh pipeline/scripts/terraform-apply.sh

# Destroy Simple Example:
#   <<: *template
#   stage: destroy
#   before_script:
#   - cd "examples/simple"
#   script:
#   - sh pipeline/scripts/terraform-destroy.sh