stages:
- validate-simple-example

Validate Simple Example:
  stage: validate-simple-example
  image: johnmorsley/alpine-with-terraform
  script:
  - sh pipeline/scripts/terraform-validate.sh "examples/simple"