stages:
- validate
- plan
- apply
- destroy

image: johnmorsley/alpine-with-terraform:0.14.2

before_script:
- export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
- export AWS_ACCESS_KEY=$AWS_ACCESS_KEY
- export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

.template: &template
  only:
  - master

.validate_template: &validate_template
  <<: *template
  stage: validate
  script:
  - sh $CI_PROJECT_DIR/pipeline/scripts/terraform-validate.sh

Validate Simple Example:
  <<: *validate_template
  #stage: validate
  before_script:
  - cd examples/simple
  # script:
  # - sh $CI_PROJECT_DIR/pipeline/scripts/terraform-validate.sh

Validate Complex Example:
  <<: *validate_template
  #stage: validate
  before_script:
  - cd examples/complex
  # script:
  # - sh $CI_PROJECT_DIR/pipeline/scripts/terraform-validate.sh

Validate RKE Example:
  <<: *validate_template
  #stage: validate
  before_script:
  - cd examples/rke
  # script:
  # - sh $CI_PROJECT_DIR/pipeline/scripts/terraform-validate.sh

  # Plan Simple Example:
#   <<: *template
#   stage: plan
#   before_script:
#   - cd "examples/simple"
#   script:
#   - sh pipeline/scripts/terraform-plan.sh

# Apply Simple Example:
#   <<: *template
#   stage: apply
#   before_script:
#   - cd "examples/simple"
#   script:
#   - sh pipeline/scripts/terraform-apply.sh

# Destroy Simple Example:
#   <<: *template
#   stage: destroy
#   before_script:
#   - cd "examples/simple"
#   script:  
#   - sh pipeline/scripts/terraform-destroy.sh